spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 7ee9141e84e43f088422
            clientSecret: 2bf9e861d34e3711e97c32ac5ed9bbf9c44a4aed
          google:
            clientId: 1024751746161-qql8i6d801f9kbg2kmoii5pjurgc9joj.apps.googleusercontent.com
            clientSecret: Szx_AgZZ6z0JIrZS4Z1TlJZ1